apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: argo
spec:
  containers:
    - name: kaniko
      image: repositories.nioint.com/adas/ado/aiotceo/kaniko-executor:v1.6.0
      args:
        - "--context=git://zhendong.pan:tVii9rr3RV4r_uuqqdw8@git.nevint.com/adops/yearning.git#refs/heads/master"
        - "--destination=repositories.nioint.com/adas/yearning:3.1.0"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
        items:
          - key: .dockerconfigjson
            path: config.json
