apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yearning
  name: yearning
  namespace: foundation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yearning
  template:
    metadata:
      labels:
        app: yearning
    spec:
      containers:
        - image: adas-hub.nioint.com/yearning:v0.3
          name: yearning
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - "./Yearning install && ./Yearning run"
          env:
            - name: MYSQL_ADDR
              value: "10.130.114.44:30999"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: "Yearning"
            - name: IS_DOCKER
              value: "docker"
            - name: SECRET_KEY
              value: "dbcjqheupqjsuwsm"
          ports:
            - containerPort: 8000
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 2
        - image: adas-hub.nioint.com/juno:v0.1
          name: juno
          imagePullPolicy: Always
          ports:
            - containerPort: 50001
              name: web
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 250m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: yearning-svc
  namespace: foundation
spec:
  selector:
    app: yearning
  ports:
    - name: yearning
      port: 80
      protocol: TCP
      targetPort: 8000
  sessionAffinity: None
  type: ClusterIP
